name: CI/CD for Node.js with Dokku

on:
  pull_request:
    branches:
      - main   # Run workflow for PRs targeting the `main` branch
  push:
    branches:
      - main   # Deploy to staging on pushes to `main`
    tags:
      - 'v*'   # Deploy to production on versioned tags (e.g., v1.0.0)

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Dokku Production
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST_PRODUCTION }}
          DOKKU_APP: ${{ secrets.DOKKU_APP_PRODUCTION }}
          DOKKU_KEY: ${{ secrets.DOKKU_KEY }}
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H $DOKKU_HOST >> ~/.ssh/known_hosts
          echo "$DOKKU_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git remote add dokku dokku@$DOKKU_HOST:$DOKKU_APP
          git push -f dokku HEAD:main 